# Generated by Django 5.2.5 on 2025-08-10 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("licence_number", models.CharField(max_length=255)),
                (
                    "availability_status",
                    models.CharField(
                        choices=[("AV", "Available"), ("AS", "Assigned")], max_length=2
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
