# Generated by Django 5.2.5 on 2025-08-10 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrentPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("latitude", models.DecimalField(decimal_places=2, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("licence_plate", models.CharField(max_length=255)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("VA", "Van"), ("TR", "Truck")], max_length=2
                    ),
                ),
                ("max_capacity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cost_per_km", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "availability_status",
                    models.CharField(
                        choices=[("AV", "Available"), ("AS", "Assigned")], max_length=2
                    ),
                ),
                (
                    "current_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vehicle.currentposition",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
